name: CandorTrial
version: '${project.version}'
main: com.berttowne.candortrial.CandorTrial
api-version: '1.21'
commands:
    teleport:
        description: Teleport to a specific location
        usage: /teleport <x> <y> <z>
        permission: candortrial.teleport
        aliases: [tp]